#!/usr/bin/env bash
# Installs and taps all my favorite tools. Should work across MacOs & Darwin

# Taps
brew tap "buo/cask-upgrade"
brew tap "noahgorstein/tap"

# Install GNU core utilities (those that come with OS X are outdated)
brew install 'coreutils'

# Install GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed
brew install 'findutils'

# S-tier tools
brew install 'awscli'
brew install 'git'
brew install 'git-delta'
brew install 'tree'
brew install 'wget'
brew install 'ripgrep'
brew install 'fish'
brew install 'fisher'
brew install 'jq'
brew install 'yq'
brew install 'fd'
brew install 'bat'
brew install 'bat-extras'
brew install 'fzf'
brew install 'stow'

# zsh plugins
brew install 'zsh-autosuggestions'
brew install 'zsh-syntax-highlighting'
brew install 'olets/tap/zsh-abbr'
brew install 'zoxide'

# Git extensions
brew install 'git-lfs'

# Github
brew install 'gh'
brew install 'hub'

# Tmux
brew install 'tmux'
brew install 'tpm'

# Languages
brew install 'go'
brew install 'golangci-lint'
brew install 'pyenv'
brew install 'node'
brew install 'python'

# Networking
brew install 'mtr'
brew install 'nmap'
brew install 'net-tools'

# Containers-related
brew install 'docker'
brew install 'stern'
brew install 'eksctl'
brew install 'helm'
brew install 'kubectl'
