#!/usr/bin/env bash

set -euo pipefail

cd "$HOME"
mkdir -p "$HOME/workplace"
echo "Cloning dotfiles directory to $HOME/workplace/dotfiles"
git -C repo pull || git clone git@github.com:AndrewSirenko/dotfiles.git workplace/dotfiles
cd "$HOME/workplace/dotfiles"

echo "Stowing dotfiles"
./symlink.sh

echo "Cloning zsh plugins"
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/powerlevel10k
git clone https://github.com/zsh-users/zsh-autosuggestions ~/.zsh/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.zsh/zsh-syntax-highlighting
curl -sSfL https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | sh
git clone https://github.com/olets/zsh-abbr --single-branch --branch v5 --depth 1 ~/.zsh/zsh-abbr

echo "Checking if stow adopted anything. See diff below, correct changes, and follow rest of script"
git diff --exit-code # Check if stow adopted anything, if so stop script early to observe
chsh -s /usr/bin/zsh "$USER"
./reload.zsh
cd "$HOME"
