#!/usr/bin/env bash
# Moves dotfiles to the needed places

dry_run="0"
tempdir="/tmp/dev-env"

if [ -z "$XDG_CONFIG_HOME" ]; then
    echo "no xdg config home"
    echo "using ~/.config"
    XDG_CONFIG_HOME=$HOME/.config
fi

if [ -z "$DEV_ENV" ]; then
    echo "env var DEV_ENV needs to be present"
    exit 1
fi

if [[ $1 == "--dry" ]]; then
    dry_run="1"
fi

log() {
    if [[ $dry_run == "1" ]]; then
        echo "[DRY_RUN]: $1"
    else
        echo "$1"
    fi
}

log "env: $DEV_ENV"

move_dir() {
    log "copying over files from: $1"
        pushd $1 &> /dev/null
        (
            configs=`find . -mindepth 1 -maxdepth 1 -type d`
            for c in $configs; do
                directory=${2%/}/${c#./}
                log "    removing: rm -rf $directory"

                if [[ $dry_run == "0" ]]; then
                    rm -rf $directory
                fi

                log "    copying env: cp $c $2"
                if [[ $dry_run == "0" ]]; then
                    cp -r ./$c $2
                fi
            done

        )
        popd &> /dev/null
}

move_file() {
    log "removing: $2"
        if [[ $dry_run == "0" ]]; then
            rm $2
        fi
        log "copying: $1 to $2"
        if [[ $dry_run == "0" ]]; then
            cp $1 $2
        fi
}

move_dir $DEV_ENV/env/config $XDG_CONFIG_HOME

# Classic Dotfiles
move_file $DEV_ENV/env/zshrc $HOME/.zshrc
move_file $DEV_ENV/env/vimrc $HOME/.vimrc
move_file $DEV_ENV/env/aliases $HOME/.aliases
move_file $DEV_ENV/env/gitconfig $HOME/.gitconfig
move_file $DEV_ENV/env/gitignore_global $HOME/.gitignore_global
move_file $DEV_ENV/env/p10k.zsh $HOME/.p10k.zsh
move_file $DEV_ENV/env/aliases $HOME/.aliases

# Claude Code settings
move_dir $DEV_ENV/env/.claude $HOME/.claude
