#!/usr/bin/env bash

# Local config
[[ ! -f ~/.config/local-configs/local.zsh ]] || source ~/.config/local-configs/local.zsh

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Include helper fcn
include () {
    [[ -f "$1" ]] && source "$1"
}

# Enter vim mode with <esc>
set -o vi

# Source some zsh plugins
source $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source $(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source $(brew --prefix)/share/zsh-abbr/zsh-abbr.zsh
eval "$(zoxide init zsh)"

zstyle ':completion:*' menu select

# Prefer gnu versions over free-bsd versions on mac (e.g. sed)
PATH="$(brew --prefix)/opt/gnu-sed/libexec/gnubin:$PATH"
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Case insensitive completions
autoload bashcompinit && bashcompinit
autoload -Uz compinit && compinit
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'

# aws completions and on-partial auto-prompt
complete -C "$(brew --prefix)/bin/aws_completer" aws
export AWS_CLI_AUTO_PROMPT=on-partial

# Aliases
include "$HOME/.aliases"


# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
source ~/powerlevel10k/powerlevel10k.zsh-theme
